# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: 			 /blog/:year/:month/:day/:title
# relative_permalinks: true		# not supported in Jekyll >= 3.0

# Setup
title:               TBD
tagline:             'Scattered Technical Notes'
description:         'This is a collection of scattered technical notes on various topics.'
url:                 https://coderik.github.io/
baseurl:             ''
paginate:            5
excerpt_separator:   <!--more-->

# About/contact
author:
  name:              Coderik
  url:               https://twitter.com/Coderik
  email:             coderiks@gmail.com

# Custom vars
version:             0.1.0

gems: 				 [jekyll-paginate]
