# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: 			 /blog/:year/:month/:day/:title
# relative_permalinks: true		# not supported in Jekyll >= 3.0

# Setup
title:               TBD
tagline:             'Scattered Technical Notes'
description:         'Watchout! Work is still in progress here.'
url:                 http://127.0.0.1:4000/
baseurl:             ''
paginate:            5
excerpt_separator:   <!--more-->

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             0.1.0

gems: 				 [jekyll-paginate]
